export const IMAGES = {
  ls: require('./iconCard/ls.png'),
  war: require('./iconCard/war.png'),
  geo: require('./iconCard/geo.png'),
  money: require('./iconCard/money.png'),
  eat: require('./iconCard/eat.png'),
  game: require('./iconCard/game.png'),
  book: require('./iconCard/book.png'),
  art: require('./iconCard/art.png'),
  story: require('./iconCard/story.png'),
  cinima: require('./iconCard/cinima.png'),
  tv: require('./iconCard/tv.png'),
  lit: require('./iconCard/lit.png'),
  music: require('./iconCard/music.png'),
  science: require('./iconCard/science.png'),
  all: require('./iconCard/all.png'),
  tradi: require('./iconCard/tradi.png'),
  animal: require('./iconCard/animal.png'),
  sport: require('./iconCard/sport.png'),
  transport: require('./iconCard/transport.png'),
  technology: require('./iconCard/technology.png'),
  lang: require('./iconCard/lang.png'),
  team: require('./iconCard/team.png'),
};
